### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Maverickthenoob**
Remove malicious links from README

### CODE REVIEW

**Review by Blaksmith — APPROVED** [review]

**Comment by SlimePuppy** [comment]
Approved

**Review by SlimePuppy — APPROVED** [review]

**Comment by SlimePuppy** [comment]
Should also update freenode to a suitable channel on discord.

Readme:
on #catcoin-dev on IRC. (on the freenode <http://www.freenode.net/> network)

**Comment by Maverickthenoob** [comment]
Agree, just wanted to sort out the critical stuff first.

**Comment by SlimePuppy** [comment]
Roj

**Pull request merged**
